### ISSUE TITLE
Electron Daemon at startup making all electron based apps run really quickly

### ISSUE THREAD

**Issue by Ornataweaver** [sindresorhus/run-electron#1]
I had this in mind, and I remember opening an issue:
https://github.com/electron/electron/issues/12732
They didn't respond that much.

**Comment by sindresorhus** [comment]
This module is for use when developing Electron apps, not for production.

**Comment by Ornataweaver** [comment]
Sorry, I'm working on sth I call #UserStoryHub, I don't know how else to make my ideas reach industry.
In the hub ideas would compete, so the industry will know the top needs of people.
Thank you for your time.
